version: "3.1"

services: 
  ui:
    restart: unless-stopped
    container_name: ui
    image: ui
    build:
      context: ./projfrontend
      dockerfile: ./Dockerfile
    volumes:
      - ./projfrontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    restart: unless-stopped
    container_name: backend
    image: backend
    build:
      context: ./projbackend
      dockerfile: ./Dockerfile
    volumes:
      - ./projbackend:/api/app
      - /api/app/node_modules
    ports:
      - "7000:7000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge