# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: End-to-end tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          working-directory: ./frontend
          start: docker-compose up -d
          wait-on: 'http://localhost:3000'
